DROP TABLE IF EXISTS customization_options CASCADE; 
CREATE TABLE customization_options ( custom_id serial NOT NULL PRIMARY KEY, custom_name character varying(70) NOT NULL, cost money NOT NULL );
DROP TABLE IF EXISTS features CASCADE; 
CREATE TABLE features ( feat_id serial NOT NULL PRIMARY KEY, feat_name character varying(70) NOT NULL );
DROP TABLE IF EXISTS customer CASCADE; 
CREATE TABLE customer ( cus_id serial NOT NULL PRIMARY KEY, name character varying(70) NOT NULL, ref_type character varying(70) NOT NULL, ref_origin character varying(70) NOT NULL );
DROP TABLE IF EXISTS employee CASCADE; 
CREATE TABLE employee ( emp_id serial NOT NULL PRIMARY KEY, emp_name character varying(70) NOT NULL, commission numeric(5,2) NOT NULL, CONSTRAINT value_is_percentage CHECK (((commission >= (0)::numeric) AND (commission < (100)::numeric) )) );
DROP TABLE IF EXISTS trade_in CASCADE; 
CREATE TABLE trade_in ( trade_id serial NOT NULL PRIMARY KEY, vin integer NOT NULL REFERENCES car(vin), miles integer NOT NULL, condition character varying(250) NOT NULL, value money NOT NULL );
DROP TABLE IF EXISTS financing CASCADE; 
CREATE TABLE financing ( fin_id serial NOT NULL PRIMARY KEY, amount money NOT NULL, type character varying(250) NOT NULL, name character varying(70) NOT NULL, addr character varying(100) NOT NULL );
DROP TABLE IF EXISTS payment CASCADE; 
CREATE TABLE payment ( payment_id serial NOT NULL PRIMARY KEY, amount money NOT NULL, trade_id integer REFERENCES trade_in(trade_id) ON DELETE CASCADE, fin_id integer REFERENCES financing(fin_id) ON DELETE CASCADE );
DROP TABLE IF EXISTS car CASCADE; 
CREATE TABLE car ( vin integer NOT NULL PRIMARY KEY, sticker_price money NOT NULL, make character varying(70) NOT NULL, model character varying(70) NOT NULL, year integer NOT NULL, color character varying(70) NOT NULL, is_new boolean NOT NULL, is_sold boolean NOT NULL, min_price money NOT NULL, mileage integer NOT NULL );
DROP TABLE IF EXISTS warranty CASCADE; 
CREATE TABLE warranty ( warranty_id serial NOT NULL PRIMARY KEY, type character varying(70) NOT NULL, cost money NOT NULL, duration integer NOT NULL, miles integer NOT NULL );
DROP TABLE IF EXISTS sale CASCADE; 
CREATE TABLE sale ( sale_id serial NOT NULL PRIMARY KEY, is_approved boolean NOT NULL, price money NOT NULL, date date NOT NULL, emp_requested boolean NOT NULL, tax_rate numeric(5,2) NOT NULL, license_fee money NOT NULL, cus_id integer NOT NULL REFERENCES customer(cus_id) ON DELETE CASCADE, vin integer NOT NULL REFERENCES car(vin) ON DELETE CASCADE, emp_id integer NOT NULL REFERENCES employee(emp_id) ON DELETE CASCADE, payment_id integer NOT NULL REFERENCES payment(payment_id) ON DELETE CASCADE, warranty_id integer NOT NULL REFERENCES warranty(warranty_id) ON DELETE CASCADE, CONSTRAINT value_is_percentage CHECK (((tax_rate >= (0)::numeric) AND (tax_rate < (100)::numeric) )) );
DROP TABLE IF EXISTS has_features CASCADE; 
CREATE TABLE has_features ( feat_id integer NOT NULL REFERENCES features(feat_id) ON DELETE CASCADE, vin integer NOT NULL REFERENCES car(vin) ON DELETE CASCADE, PRIMARY KEY(feat_id, vin) );
DROP TABLE IF EXISTS has_customization CASCADE; 
CREATE TABLE has_customization ( custom_id integer NOT NULL REFERENCES customization_options(custom_id) ON DELETE CASCADE, sale_id integer NOT NULL REFERENCES sale(sale_id) ON DELETE CASCADE, PRIMARY KEY(custom_id, sale_id) );
INSERT INTO features (feat_id, feat_name) VALUES (0, 'AC');
INSERT INTO features (feat_id, feat_name) VALUES (1, 'Heated Seats');
INSERT INTO features (feat_id, feat_name) VALUES (2, 'Power Windows');
INSERT INTO features (feat_id, feat_name) VALUES (3, 'Sunroof');
INSERT INTO features (feat_id, feat_name) VALUES (4, 'Leather Seats');
INSERT INTO features (feat_id, feat_name) VALUES (5, 'Sirius XM Radio');
INSERT INTO customization_options (custom_id, custom_name, cost) VALUES (0, 'AC', 151);
INSERT INTO customization_options (custom_id, custom_name, cost) VALUES (1, 'Heated Seats', 375);
INSERT INTO customization_options (custom_id, custom_name, cost) VALUES (2, 'Power Windows', 302);
INSERT INTO customization_options (custom_id, custom_name, cost) VALUES (3, 'Sunroof', 194);
INSERT INTO customization_options (custom_id, custom_name, cost) VALUES (4, 'Leather Seats', 141);
INSERT INTO customization_options (custom_id, custom_name, cost) VALUES (5, 'Sirius XM Radio', 135);
INSERT INTO warranty (type, cost, duration, miles) VALUES ('Standard', 0, 60, 5000);
INSERT INTO warranty (type, cost, duration, miles) VALUES ('Extended', 100, 120, 10000);
INSERT INTO warranty (type, cost, duration, miles) VALUES ('Limited', 0, 30, 2000);
INSERT INTO customer (name, ref_type, ref_origin) VALUES ('Frank Murray', 'none', 'none');
INSERT INTO customer (name, ref_type, ref_origin) VALUES ('Jan Scott', 'web', 'facebook.com');
INSERT INTO customer (name, ref_type, ref_origin) VALUES ('Adrian Blake', 'mouth', 'Emma Peake');
INSERT INTO customer (name, ref_type, ref_origin) VALUES ('Emma Peake', 'web', 'cars.com');
INSERT INTO customer (name, ref_type, ref_origin) VALUES ('Adam Parr', 'tv ad', 'channel 3');
INSERT INTO employee (emp_name, commission) VALUES ('Jim Friendly', 30);
INSERT INTO employee (emp_name, commission) VALUES ('Diane Graham', 10);
INSERT INTO employee (emp_name, commission) VALUES ('Keven Greene', 10);
INSERT INTO employee (emp_name, commission) VALUES ('Joshua Fraser', 5);
INSERT INTO employee (emp_name, commission) VALUES ('Brian Morrison', 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (555555, 10000, 'ford', 'fusion', 2010, 'silver', true, true, 0.3, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (666666, 15000, 'ford', 'focus', 2016, 'black', true, true, 0.5, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (777777, 9000, 'ford', 'mustang', 2000, 'white', true, true, 0.1, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (652490, 14622, 'Ford', 'mustang', 1997, 'red', true, false, 0.0, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (166296, 19224, 'Ford', 'focus', 1997, 'silver', true, false, 0.0, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (309755, 8099, 'Ford', 'fusion', 1997, 'red', true, false, 0.0, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (305049, 12382, 'Ford', 'taurus', 1997, 'black', true, false, 0.3, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (440426, 15942, 'Ford', 'mustang', 1998, 'silver', true, false, 0.1, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (633183, 11542, 'Ford', 'focus', 1998, 'silver', true, false, 0.0, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (453536, 9034, 'Ford', 'fusion', 1998, 'red', true, false, 0.3, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (847822, 7276, 'Ford', 'taurus', 1998, 'red', true, false, 0.3, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (191591, 19757, 'Ford', 'mustang', 1999, 'silver', true, false, 0.0, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (271303, 18277, 'Ford', 'focus', 1999, 'silver', true, false, 0.2, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (702124, 19166, 'Ford', 'fusion', 1999, 'red', true, false, 0.2, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (762866, 7794, 'Ford', 'taurus', 1999, 'black', true, false, 0.1, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (162460, 14782, 'Ford', 'mustang', 2000, 'silver', true, false, 0.3, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (933012, 17902, 'Ford', 'focus', 2000, 'black', true, false, 0.4, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (126890, 6319, 'Ford', 'fusion', 2000, 'red', true, false, 0.0, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (300185, 8507, 'Ford', 'taurus', 2000, 'red', true, false, 0.0, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (970087, 10311, 'Ford', 'mustang', 2001, 'red', true, false, 0.3, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (350571, 13721, 'Ford', 'focus', 2001, 'red', true, false, 0.0, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (949576, 17733, 'Ford', 'fusion', 2001, 'red', true, false, 0.0, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (768536, 17967, 'Ford', 'taurus', 2001, 'red', true, false, 0.4, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (510724, 8082, 'Ford', 'mustang', 2002, 'silver', true, false, 0.1, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (304175, 15919, 'Ford', 'focus', 2002, 'black', true, false, 0.1, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (211507, 7610, 'Ford', 'fusion', 2002, 'black', true, false, 0.2, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (710691, 6886, 'Ford', 'taurus', 2002, 'red', true, false, 0.0, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (571855, 14184, 'Ford', 'mustang', 2003, 'red', true, false, 0.0, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (644742, 10704, 'Ford', 'focus', 2003, 'black', true, false, 0.3, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (487702, 11092, 'Ford', 'fusion', 2003, 'red', true, false, 0.0, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (257487, 14344, 'Ford', 'taurus', 2003, 'silver', true, false, 0.3, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (809285, 8880, 'Ford', 'mustang', 2004, 'black', true, false, 0.2, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (935348, 12286, 'Ford', 'focus', 2004, 'red', true, false, 0.1, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (787582, 9766, 'Ford', 'fusion', 2004, 'red', true, false, 0.3, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (519760, 5238, 'Ford', 'taurus', 2004, 'silver', true, false, 0.2, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (511715, 15155, 'Ford', 'mustang', 2005, 'black', true, false, 0.3, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (154941, 15399, 'Ford', 'focus', 2005, 'silver', true, false, 0.2, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (796376, 16687, 'Ford', 'fusion', 2005, 'silver', true, false, 0.1, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (123035, 19569, 'Ford', 'taurus', 2005, 'red', true, false, 0.4, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (684516, 7698, 'Ford', 'mustang', 2006, 'black', true, false, 0.3, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (739239, 15261, 'Ford', 'focus', 2006, 'red', true, false, 0.4, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (424400, 17032, 'Ford', 'fusion', 2006, 'red', true, false, 0.0, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (524260, 15105, 'Ford', 'taurus', 2006, 'silver', true, false, 0.2, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (358469, 19678, 'Ford', 'mustang', 2007, 'red', true, false, 0.4, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (682613, 18545, 'Ford', 'focus', 2007, 'black', true, false, 0.0, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (712978, 5434, 'Ford', 'fusion', 2007, 'red', true, false, 0.1, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (951616, 15846, 'Ford', 'taurus', 2007, 'red', true, false, 0.2, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (206436, 12742, 'Ford', 'mustang', 2008, 'black', true, false, 0.3, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (112044, 12466, 'Ford', 'focus', 2008, 'red', true, false, 0.2, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (267628, 18852, 'Ford', 'fusion', 2008, 'red', true, false, 0.4, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (864867, 13018, 'Ford', 'taurus', 2008, 'red', true, false, 0.2, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (258940, 16867, 'Ford', 'mustang', 2009, 'red', true, false, 0.4, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (866064, 13074, 'Ford', 'focus', 2009, 'black', true, false, 0.4, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (612873, 9360, 'Ford', 'fusion', 2009, 'black', true, false, 0.2, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (843010, 18524, 'Ford', 'taurus', 2009, 'red', true, false, 0.4, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (196298, 16214, 'Ford', 'mustang', 2010, 'silver', true, false, 0.1, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (917127, 11241, 'Ford', 'focus', 2010, 'red', true, false, 0.4, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (113847, 16846, 'Ford', 'fusion', 2010, 'silver', true, false, 0.2, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (396369, 15493, 'Ford', 'taurus', 2010, 'black', true, false, 0.2, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (750090, 6071, 'Ford', 'mustang', 2011, 'black', true, false, 0.4, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (242964, 14015, 'Ford', 'focus', 2011, 'black', true, false, 0.0, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (848033, 6206, 'Ford', 'fusion', 2011, 'red', true, false, 0.4, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (855493, 13486, 'Ford', 'taurus', 2011, 'black', true, false, 0.3, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (962361, 18054, 'Ford', 'mustang', 2012, 'black', true, false, 0.0, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (478140, 19620, 'Ford', 'focus', 2012, 'silver', true, false, 0.2, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (348724, 13434, 'Ford', 'fusion', 2012, 'black', true, false, 0.2, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (343122, 11575, 'Ford', 'taurus', 2012, 'silver', true, false, 0.2, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (402963, 10469, 'Ford', 'mustang', 2013, 'black', true, false, 0.0, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (509539, 12754, 'Ford', 'focus', 2013, 'black', true, false, 0.2, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (283741, 17936, 'Ford', 'fusion', 2013, 'black', true, false, 0.4, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (786925, 14768, 'Ford', 'taurus', 2013, 'black', true, false, 0.0, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (154742, 19044, 'Ford', 'mustang', 2014, 'black', true, false, 0.0, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (423407, 14345, 'Ford', 'focus', 2014, 'red', true, false, 0.0, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (937832, 5155, 'Ford', 'fusion', 2014, 'silver', true, false, 0.3, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (457578, 18682, 'Ford', 'taurus', 2014, 'silver', true, false, 0.2, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (256605, 16899, 'Ford', 'mustang', 2015, 'red', true, false, 0.0, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (605731, 10194, 'Ford', 'focus', 2015, 'black', true, false, 0.1, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (164513, 11618, 'Ford', 'fusion', 2015, 'black', true, false, 0.0, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (529822, 14223, 'Ford', 'taurus', 2015, 'red', true, false, 0.3, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (979268, 15378, 'Ford', 'mustang', 2016, 'black', true, false, 0.1, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (680004, 16780, 'Ford', 'focus', 2016, 'black', true, false, 0.0, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (964758, 14398, 'Ford', 'fusion', 2016, 'red', true, false, 0.1, 0);
INSERT INTO car (vin, sticker_price, make, model, year, color, is_new, is_sold, min_price, mileage) VALUES (909245, 19661, 'Ford', 'taurus', 2016, 'red', true, false, 0.1, 0);
INSERT INTO trade_in (vin, miles, condition, value) VALUES (333333, 25000, 'good', 5000);
INSERT INTO financing (amount, type, name, addr) VALUES (15000, 'bank', 'bank of america', '123 Fake St.');
INSERT INTO financing (amount, type, name, addr) VALUES (4000, 'dealership', 'ford', '543 False Ave.');
INSERT INTO payment (amount, trade_id, fin_id) VALUES (10000, null, null);
INSERT INTO payment (amount, trade_id, fin_id) VALUES (10000, null, 1);
INSERT INTO payment (amount, trade_id, fin_id) VALUES (9000, 1, 2);
INSERT INTO sale (is_approved, price, date, emp_requested, tax_rate, license_fee, cus_id, vin, emp_id, payment_id, warranty_id) VALUES (false, 10000, '01/01/2017', false, 0.05, 29, 2, 555555, 3, 1, 2);
INSERT INTO sale (is_approved, price, date, emp_requested, tax_rate, license_fee, cus_id, vin, emp_id, payment_id, warranty_id) VALUES (false, 15000, '01/01/2017', false, 0.05, 112, 3, 666666, 1, 2, 2);
INSERT INTO sale (is_approved, price, date, emp_requested, tax_rate, license_fee, cus_id, vin, emp_id, payment_id, warranty_id) VALUES (false, 9000, '01/01/2017', false, 0.05, 64, 3, 777777, 2, 3, 1);
