DROP TABLE IF EXISTS sale; 
DROP TABLE IF EXISTS car; 
DROP TABLE IF EXISTS has_features; 
DROP TABLE IF EXISTS has_customization; 
DROP TABLE IF EXISTS payment; 
DROP TABLE IF EXISTS trade_in; 
DROP TABLE IF EXISTS financing; 
DROP TABLE IF EXISTS employee; 
DROP TABLE IF EXISTS warranty; 
DROP TABLE IF EXISTS features; 
DROP TABLE IF EXISTS customization_options; 
DROP TABLE IF EXISTS customer; 
CREATE TABLE customization_options ( custom_id serial NOT NULL PRIMARY KEY, custom_name character varying(70) NOT NULL );
CREATE TABLE features ( feat_id serial NOT NULL PRIMARY KEY, feat_name character varying(70) NOT NULL );
CREATE TABLE customer ( cus_id serial NOT NULL PRIMARY KEY, name character varying(70) NOT NULL, ref_origin character varying(70) NOT NULL, ref_type character varying(70) NOT NULL );
CREATE TABLE employee ( emp_id integer NOT NULL PRIMARY KEY, emp_name character varying(70) NOT NULL, commission numeric(5,2) NOT NULL, CONSTRAINT value_is_percentage CHECK (((commission > (1)::numeric) AND (commission < (100)::numeric) )) );
CREATE TABLE trade_in ( trade_id serial NOT NULL PRIMARY KEY, vin integer NOT NULL, miles integer NOT NULL, condition character varying(250) NOT NULL, value money NOT NULL, date date NOT NULL );
CREATE TABLE financing ( fin_id serial NOT NULL PRIMARY KEY, amount money NOT NULL, type character varying(250) NOT NULL, name character varying(70) NOT NULL, addr character varying(100) NOT NULL );
CREATE TABLE payment ( payment_id serial NOT NULL PRIMARY KEY, amount money NOT NULL, trade_id integer NOT NULL REFERENCES trade_in(trade_id), fin_id integer NOT NULL REFERENCES financing(fin_id) );
CREATE TABLE car ( vin integer NOT NULL PRIMARY KEY, sticker_price money NOT NULL, make character varying(70) NOT NULL, model character varying(70) NOT NULL, year integer NOT NULL, is_new boolean NOT NULL, is_sold boolean NOT NULL, min_price money NOT NULL, mileage integer NOT NULL );
CREATE TABLE warranty ( warranty_id serial NOT NULL PRIMARY KEY, type character varying(70) NOT NULL, cost money NOT NULL, duration integer NOT NULL, miles integer NOT NULL );
CREATE TABLE sale ( sale_id integer NOT NULL PRIMARY KEY, is_approved boolean NOT NULL, price money NOT NULL, date date NOT NULL, emp_requested boolean NOT NULL, tax_rate numeric(5,2) NOT NULL, license_fee money NOT NULL, cus_id integer NOT NULL REFERENCES customer(cus_id), vin integer NOT NULL REFERENCES car(vin), emp_id integer NOT NULL REFERENCES employee(emp_id), payment_id integer NOT NULL REFERENCES payment(payment_id), warranty_id integer NOT NULL REFERENCES warranty(warranty_id), CONSTRAINT value_is_percentage CHECK (((tax_rate > (1)::numeric) AND (tax_rate < (100)::numeric) )) );
CREATE TABLE has_features ( feat_id integer NOT NULL REFERENCES features(feat_id), vin integer NOT NULL REFERENCES car(vin), PRIMARY KEY(feat_id, vin) );
CREATE TABLE has_customization ( custom_id integer NOT NULL REFERENCES customization_options(custom_id), sale_id integer NOT NULL REFERENCES sale(sale_id), PRIMARY KEY(custom_id, sale_id) );
